version: '3.8'

services:
  frontend:
    build:
      context: ./apps/nawy-nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000  
    depends_on:
      - backend
    networks:
      - nawy-network

  backend:
    build:
      context: ./apps/nawy-web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "1517"
      DB_NAME: apartment_db
    depends_on:
      - db
    networks:
      - nawy-network
    command: >
      sh -c "npm run build && npm run migration:run && npm run start"

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1517"
      POSTGRES_DB: apartment_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nawy-network

volumes:
  postgres-data:

networks:
  nawy-network:
